passoffice = git
createimagemap = yes
compare = none
createhistory = no
createskos = yes
creategmlprofile = no
usefirstmap = yes
#mapping = MIM-NEN3610-ONTDUBBELD
assocbyreference        = yes
#createmimformat = yes
#mimformattype = xml
nativescalars = no
